#Create a playbook for installing different application software installations
---
- name: Implementing loops
  hosts: all
  tasks:
   - name: installing s/w packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree, b: present, c: no}
      - {a: default-jdk, b: absent, c: yes}
      - {a: git, b: latest, c: yes}
... 
