---
#Ansible playbook to check if directory is present if present create a file in it.
- name: check if dir is present or not
  hosts: all
  tasks:
   - name: check if dir is present or not
     stat:
      path: /var
     register: results
   - name: display output of the above stat modules
     debug:
      var: results
   - name: create a file
     file:
      name: /var/file5
      state: touch
     when:
      results.stat.exists == true
...
